name: Flask-Application

on:
  push: 
    branches:
      - dev
      - stage
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps: 
    - uses: actions/checkout@v3 
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7" 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        serverless plugin install -n serverless-wsgi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: install npm and node
      run: npm install -g serverless

    - name: deploy
      run: serverless deploy --stage dev  



  build-stage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    steps: 
    - uses: actions/checkout@v3 
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7" 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        serverless plugin install -n serverless-wsgi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: install npm and node
      run: npm install -g serverless

    - name: deploy
      run: serverless deploy --stage stage  
  
  build-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps: 
    - uses: actions/checkout@v3 
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7" 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        serverless plugin install -n serverless-wsgi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: install npm and node
      run: npm install -g serverless

    - name: deploy
      run: serverless deploy --stage prod 





